# Generated by Django 3.2.5 on 2023-04-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="item",
            new_name="select_item",
        ),
    ]
