# Generated by Django 3.2.5 on 2022-12-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(help_text='Firstname of the user.', max_length=50)),
                ('lastname', models.CharField(help_text='Lastname of the user.', max_length=50)),
                ('username', models.CharField(help_text='The username of that user.', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Email address of the user.', max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='The phone number of the user.', max_length=12)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vendor'), (2, 'Customer')], help_text='Select the role of the user (Customer or Vendor.', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
